window = Window.New(nil, 500, 500, 'title', 'mono')
window.slider = UISlider.New(window, 30, 300, "vertical", "uiwindow")
window.slider:SetYPos(30)
window.slider:SetKnobColor(1,1,1,1)
window.slider:SetSlideColor(0,0,0,1)
window.slider:AddOnDragged(function() 
   window.info:SetText(tostring(window.slider:GetValue() * 100))
end)
window.info = UILabel.New(window, "...", "vollkorn", 1,1,1,1)
window.info:SetXPos(30)
window.info:SetYPos(30)